---
kind: pipeline
type: docker
name: build

steps:
  - name: build
    image: maven:3-openjdk-8
    user: root
    commands:
      - apt-get update
      - apt-get install -qy patch
      - ./papercut jar
