---
kind: pipeline
type: docker
name: build

steps:
  - name: build
    image: maven:3-openjdk-8
    user: root
    commands:
      - apt-get update
      - apt-get install -qy patch
      - ./papercut jar
  - name: release
    image: curlimages/curl:latest
    user: root
    commands:
      - curl https://github.com/c4milo/github-release/releases/download/v1.1.0/github-release_v1.1.0_linux_amd64.tar.gz > release.tar.gz
      - apk update
      - apk add tar
      - tar xzf release.tar.gz
      - './github-release "$DRONE_REPO" "$DRONE_COMMIT" "$DRONE_BRANCH" "Automated release, do not use this in production." "papercut-paperclip.jar"'
    environment:
      GITHUB_TOKEN:
        from_secret: mvbot_token
    when:
      branch:
        - master
      event:
        - push
