name: Java CI

on:
  push:
    tags:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1.3.0
      with:
        java-version: 11
    - uses: actions/cache@v1.1.2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Patch Papercut
      run: |
        git config --global user.email "you@example.com"
        git config --global user.name "Your Name"
        git submodule update --init --recursive
        ./papercut jar
    - name: Upload Artifact
      uses: actions/upload-artifact@v2-preview
      with:
        name: Papercut
        path: papercut-paperclip.jar
